name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file 2.8/ubuntu1804/cuda10.0/devel/Dockerfile --tag foobar:$(date +%s)
